# Use an official Node runtime as a parent image
FROM

# Set the working directory in the container
WORKDIR

# Copy package.json and package-lock.json
COPY

# Install app dependencies
RUN

# Copy the current directory contents into the container
COPY

# Build the app
RUN

# Make port 3000 available to the world outside this container
EXPOSE

# Define environment variable
ENV

# Run the app when the container launches
CMD