# Use an official Python runtime as a parent image
FROM

# Set the working directory in the container
WORKDIR

# Copy the current directory contents into the container at /app
COPY

# Install any needed packages specified in requirements.txt
RUN

# Make port 5000 available to the world outside this container
EXPOSE

# Define environment variable
ENV

# Run app.py when the container launches
CMD