# TODO-STEP 1: Choose a base image
FROM <BASE_IMAGE>

# TODO-STEP 2: Set the working directory
WORKDIR <WORKING_DIRECTORY>

# TODO-STEP 3: Copy the requirements file
COPY <SOURCE> <DESTINATION>

# TODO-STEP 4: Install the Python dependencies
RUN <COMMAND_TO_INSTALL_DEPENDENCIES>

# TODO-STEP 5: Copy the application code
COPY <SOURCE> <DESTINATION>

# TODO-STEP 6: Specify the command to run the application
CMD <COMMAND_TO_RUN_APP>